/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clamwin.antivirus;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class Reports extends javax.swing.JFrame {

    private BufferedImage closeImage = null;
    private BufferedImage minimizeImage = null;
    
    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        iconSet();
        getAndScaleImages();
        
    }
    
    private void iconSet(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/mainIcon.png")));
    }
    
    private void getAndScaleImages(){
        
        //minimize button
        try {

            minimizeImage = ImageIO.read(this.getClass().getResource("/images/minimize.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
        
	//buffered image scaled
	Image minimizeBtnDimensions = minimizeImage.getScaledInstance(lbl_btn_reports_minimize.getWidth(), lbl_btn_reports_minimize.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon MinimizeIcon = new ImageIcon(minimizeBtnDimensions);
				
	//icon set
	lbl_btn_reports_minimize.setIcon(MinimizeIcon);
        
        //close button
        try {

            closeImage = ImageIO.read(this.getClass().getResource("/images/closeButton.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
        
	//buffered image scaled
	Image closeBtnDimensions = closeImage.getScaledInstance(lbl_btn_reports_close.getWidth(), lbl_btn_reports_close.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon closeIcon = new ImageIcon(closeBtnDimensions);
				
	//icon set
	lbl_btn_reports_close.setIcon(closeIcon); 
        
        
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_preferencesScheduledAddNew_top = new javax.swing.JPanel();
        lbl_reports_title = new javax.swing.JLabel();
        lbl_btn_reports_minimize = new javax.swing.JLabel();
        lbl_btn_reports_close = new javax.swing.JLabel();
        reports_panel_outer = new javax.swing.JPanel();
        reports_panel_inner = new javax.swing.JPanel();
        btn_reports_back = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 55, 110));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_preferencesScheduledAddNew_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_reports_title.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lbl_reports_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_reports_title.setText("ClamWin Reports");
        lbl_reports_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_preferencesScheduledAddNew_top.add(lbl_reports_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 670, 20));

        lbl_btn_reports_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_reports_minimizeMouseClicked(evt);
            }
        });
        panel_preferencesScheduledAddNew_top.add(lbl_btn_reports_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 20, 10));

        lbl_btn_reports_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_reports_closeMouseClicked(evt);
            }
        });
        panel_preferencesScheduledAddNew_top.add(lbl_btn_reports_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 20));

        getContentPane().add(panel_preferencesScheduledAddNew_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 20));

        reports_panel_outer.setBackground(new java.awt.Color(64, 55, 110));
        reports_panel_outer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reports_panel_inner.setBackground(new java.awt.Color(204, 204, 204));
        reports_panel_inner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reports_back.setBackground(new java.awt.Color(173, 159, 175));
        btn_reports_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reports_back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_reports_back.setForeground(new java.awt.Color(102, 0, 153));
        btn_reports_back.setLabel("Back");
        btn_reports_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reports_backActionPerformed(evt);
            }
        });
        reports_panel_inner.add(btn_reports_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, 40));

        reports_panel_outer.add(reports_panel_inner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 780, 420));

        getContentPane().add(reports_panel_outer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_btn_reports_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_reports_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_btn_reports_minimizeMouseClicked

    private void lbl_btn_reports_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_reports_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_btn_reports_closeMouseClicked

    private void btn_reports_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reports_backActionPerformed

        MainMenu m1 = new MainMenu();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_reports_backActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_reports_back;
    private javax.swing.JLabel lbl_btn_reports_close;
    private javax.swing.JLabel lbl_btn_reports_minimize;
    private javax.swing.JLabel lbl_reports_title;
    private javax.swing.JPanel panel_preferencesScheduledAddNew_top;
    private javax.swing.JPanel reports_panel_inner;
    private javax.swing.JPanel reports_panel_outer;
    // End of variables declaration//GEN-END:variables
}
