/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clamwin.antivirus;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class Scan extends javax.swing.JFrame {
    
    private BufferedImage closeImage = null;
    private BufferedImage minimizeImage = null;
    private BufferedImage memoryImage = null;
    private BufferedImage selectedFilesImage = null;
    

    /**
     * Creates new form Scan
     */
    public Scan() {
        initComponents();
        iconSet();
        getAndScaleCloseButtonImage();
        getAndScaleMinimizeButtonImage();
        getAndScaleScanOptionImages();
        cursorChange();
    }
    
    private void iconSet(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/mainIcon.png")));
    }
        
    //scaling the image according to the jlabel
    private void getAndScaleCloseButtonImage(){
        
        try {

            closeImage = ImageIO.read(this.getClass().getResource("/images/closeButton.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
        
	//buffered image scaled
	Image closeBtnDimensions = closeImage.getScaledInstance(lbl_btn_scan_close.getWidth(), lbl_btn_scan_close.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon closeIcon = new ImageIcon(closeBtnDimensions);
				
	//icon set
	lbl_btn_scan_close.setIcon(closeIcon);
        
    }
    
    //scaling the image according to the jlabel
    private void getAndScaleMinimizeButtonImage(){
        
        try {

            minimizeImage = ImageIO.read(this.getClass().getResource("/images/minimize.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
        
	//buffered image scaled
	Image minimizeBtnDimensions = minimizeImage.getScaledInstance(lbl_btn_scan_minimize.getWidth(), lbl_btn_scan_minimize.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon MinimizeIcon = new ImageIcon(minimizeBtnDimensions);
				
	//icon set
	lbl_btn_scan_minimize.setIcon(MinimizeIcon);
        
    }
    
    //change cursor to hand
    private void cursorChange(){
        lbl_btn_scan_close.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lbl_btn_scan_minimize.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    
    //scaling the scan sub menu option images
    private void getAndScaleScanOptionImages(){
        
        //read image files
        try {

            memoryImage = ImageIO.read(this.getClass().getResource("/images/memory.png"));
            selectedFilesImage = ImageIO.read(this.getClass().getResource("/images/folder.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
       
        //getting dimension of the jlabels
	Image scanImgDimensions = memoryImage.getScaledInstance(lbl_icon_scan_bottom_inside_memory.getWidth(), lbl_icon_scan_bottom_inside_memory.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon memoryIcon = new ImageIcon(scanImgDimensions);
        
        Image updateImgDimensions = selectedFilesImage.getScaledInstance(lbl_icon_scan_bottom_inside_selectedFiles.getWidth(), lbl_icon_scan_bottom_inside_selectedFiles.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon selectedFilesIcon = new ImageIcon(updateImgDimensions);
		
        //setting images
	lbl_icon_scan_bottom_inside_memory.setIcon(memoryIcon);
        lbl_icon_scan_bottom_inside_selectedFiles.setIcon(selectedFilesIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_scan_top = new javax.swing.JPanel();
        lbl_scan_titile = new javax.swing.JLabel();
        lbl_btn_scan_minimize = new javax.swing.JLabel();
        lbl_btn_scan_close = new javax.swing.JLabel();
        panel_scan_bottom_main = new javax.swing.JPanel();
        panel_scan_bottom_inside = new javax.swing.JPanel();
        panel_scan_bottom_inside_memoryMain = new javax.swing.JPanel();
        panel_scan_bottom_inside_memory_inside = new javax.swing.JPanel();
        lbl_icon_scan_bottom_inside_memory = new javax.swing.JLabel();
        lbl_scan_bottom_inside_memory = new javax.swing.JLabel();
        panel_scan_bottom_inside_selectedFilesMain = new javax.swing.JPanel();
        panel_scan_bottom_inside_selectedFiles_inside = new javax.swing.JPanel();
        lbl_icon_scan_bottom_inside_selectedFiles = new javax.swing.JLabel();
        lbl_scan_bottom_inside_selectedFiles = new javax.swing.JLabel();
        btn_scan_MainMenu = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_scan_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_scan_titile.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lbl_scan_titile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_scan_titile.setText("ClamWin Scan");
        lbl_scan_titile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_scan_top.add(lbl_scan_titile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 670, 20));

        lbl_btn_scan_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_scan_minimizeMouseClicked(evt);
            }
        });
        panel_scan_top.add(lbl_btn_scan_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 20, 10));

        lbl_btn_scan_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_scan_closeMouseClicked(evt);
            }
        });
        panel_scan_top.add(lbl_btn_scan_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 20));

        getContentPane().add(panel_scan_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 20));

        panel_scan_bottom_main.setBackground(new java.awt.Color(64, 55, 110));
        panel_scan_bottom_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_scan_bottom_inside.setBackground(new java.awt.Color(107, 91, 170));
        panel_scan_bottom_inside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_scan_bottom_inside_memoryMain.setBackground(new java.awt.Color(221, 73, 108));
        panel_scan_bottom_inside_memoryMain.setToolTipText("Scan computer memory for viruses");
        panel_scan_bottom_inside_memoryMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_scan_bottom_inside_memoryMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_scan_bottom_inside_memoryMainMouseClicked(evt);
            }
        });
        panel_scan_bottom_inside_memoryMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_scan_bottom_inside_memory_inside.setBackground(new java.awt.Color(255, 0, 72));
        panel_scan_bottom_inside_memory_inside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_scan_bottom_inside_memory_inside.add(lbl_icon_scan_bottom_inside_memory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 70));

        panel_scan_bottom_inside_memoryMain.add(panel_scan_bottom_inside_memory_inside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 194, 185));

        lbl_scan_bottom_inside_memory.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        lbl_scan_bottom_inside_memory.setForeground(new java.awt.Color(255, 255, 255));
        lbl_scan_bottom_inside_memory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_scan_bottom_inside_memory.setText("Memory");
        panel_scan_bottom_inside_memoryMain.add(lbl_scan_bottom_inside_memory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 40));

        panel_scan_bottom_inside.add(panel_scan_bottom_inside_memoryMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 194, 236));

        panel_scan_bottom_inside_selectedFilesMain.setBackground(new java.awt.Color(240, 102, 58));
        panel_scan_bottom_inside_selectedFilesMain.setToolTipText("Scan selected files for viruses");
        panel_scan_bottom_inside_selectedFilesMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_scan_bottom_inside_selectedFilesMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_scan_bottom_inside_selectedFilesMainMouseClicked(evt);
            }
        });
        panel_scan_bottom_inside_selectedFilesMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_scan_bottom_inside_selectedFiles_inside.setBackground(new java.awt.Color(230, 65, 14));
        panel_scan_bottom_inside_selectedFiles_inside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_scan_bottom_inside_selectedFiles_inside.add(lbl_icon_scan_bottom_inside_selectedFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 70));

        panel_scan_bottom_inside_selectedFilesMain.add(panel_scan_bottom_inside_selectedFiles_inside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 194, 185));

        lbl_scan_bottom_inside_selectedFiles.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        lbl_scan_bottom_inside_selectedFiles.setForeground(new java.awt.Color(255, 255, 255));
        lbl_scan_bottom_inside_selectedFiles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_scan_bottom_inside_selectedFiles.setText("Selected Files");
        panel_scan_bottom_inside_selectedFilesMain.add(lbl_scan_bottom_inside_selectedFiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 40));

        panel_scan_bottom_inside.add(panel_scan_bottom_inside_selectedFilesMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 194, 236));

        btn_scan_MainMenu.setBackground(new java.awt.Color(173, 159, 175));
        btn_scan_MainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_scan_MainMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_scan_MainMenu.setForeground(new java.awt.Color(102, 0, 153));
        btn_scan_MainMenu.setLabel("Main Menu");
        btn_scan_MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scan_MainMenuActionPerformed(evt);
            }
        });
        panel_scan_bottom_inside.add(btn_scan_MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 120, 40));

        panel_scan_bottom_main.add(panel_scan_bottom_inside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 780, 400));

        getContentPane().add(panel_scan_bottom_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //minimize button action on mouse click
    private void lbl_btn_scan_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_scan_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_btn_scan_minimizeMouseClicked

    //close button action on mouse click
    private void lbl_btn_scan_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_scan_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_btn_scan_closeMouseClicked

    //main menu button action on mouse clikc
    private void btn_scan_MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scan_MainMenuActionPerformed
        MainMenu m1 = new MainMenu();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_scan_MainMenuActionPerformed

    //mouse click on the memory option
    private void panel_scan_bottom_inside_memoryMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_scan_bottom_inside_memoryMainMouseClicked
        MemoryScanStatus mst1 = new MemoryScanStatus();
        mst1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panel_scan_bottom_inside_memoryMainMouseClicked

    //mouse click on the selected files option
    private void panel_scan_bottom_inside_selectedFilesMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_scan_bottom_inside_selectedFilesMainMouseClicked
        SelectedFiles sf1 = new SelectedFiles();
        sf1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panel_scan_bottom_inside_selectedFilesMainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_scan_MainMenu;
    private javax.swing.JLabel lbl_btn_scan_close;
    private javax.swing.JLabel lbl_btn_scan_minimize;
    private javax.swing.JLabel lbl_icon_scan_bottom_inside_memory;
    private javax.swing.JLabel lbl_icon_scan_bottom_inside_selectedFiles;
    private javax.swing.JLabel lbl_scan_bottom_inside_memory;
    private javax.swing.JLabel lbl_scan_bottom_inside_selectedFiles;
    private javax.swing.JLabel lbl_scan_titile;
    private javax.swing.JPanel panel_scan_bottom_inside;
    private javax.swing.JPanel panel_scan_bottom_inside_memoryMain;
    private javax.swing.JPanel panel_scan_bottom_inside_memory_inside;
    private javax.swing.JPanel panel_scan_bottom_inside_selectedFilesMain;
    private javax.swing.JPanel panel_scan_bottom_inside_selectedFiles_inside;
    private javax.swing.JPanel panel_scan_bottom_main;
    private javax.swing.JPanel panel_scan_top;
    // End of variables declaration//GEN-END:variables
}
