/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clamwin.antivirus;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class SplashScreen extends javax.swing.JFrame {

    private BufferedImage iconImage = null;
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        getAndScaleMainIconImage();
        iconSet();
        

    }
    
    private void iconSet(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/mainIcon.png")));
    }
    
    //scaling the image according to the jlabel
    private void getAndScaleMainIconImage(){
        
        try {

            iconImage = ImageIO.read(this.getClass().getResource("/images/clamwin-pngwave.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
        
	//buffered image scaled
	Image iconBtnDimensions = iconImage.getScaledInstance(lbl_img_splashscreen_icon.getWidth(), lbl_img_splashscreen_icon.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon MinimizeIcon = new ImageIcon(iconBtnDimensions);
				
	//icon set
	lbl_img_splashscreen_icon.setIcon(MinimizeIcon);
        
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_splashscreen_bottom = new javax.swing.JPanel();
        lbl_img_splashscreen_icon = new javax.swing.JLabel();
        progressBar_splashscreen = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClamWin Free Antivirus");
        setName("SplashScreen"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_splashscreen_bottom.setBackground(new java.awt.Color(64, 2, 103));

        javax.swing.GroupLayout panel_splashscreen_bottomLayout = new javax.swing.GroupLayout(panel_splashscreen_bottom);
        panel_splashscreen_bottom.setLayout(panel_splashscreen_bottomLayout);
        panel_splashscreen_bottomLayout.setHorizontalGroup(
            panel_splashscreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_splashscreen_bottomLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(panel_splashscreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img_splashscreen_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_splashscreen_bottomLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(progressBar_splashscreen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        panel_splashscreen_bottomLayout.setVerticalGroup(
            panel_splashscreen_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_splashscreen_bottomLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lbl_img_splashscreen_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar_splashscreen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(panel_splashscreen_bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void diposea(){
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SplashScreen splash = new SplashScreen();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                splash.setVisible(true);
                
            }
            
        });
        
        
        splash.progressBar_splashscreen.setStringPainted(true);

        int k;
        for(k = 0; k < 100; k++){
            
            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
                e.printStackTrace();;
            }
            
            splash.progressBar_splashscreen.setValue(k);
            
        }
        
        //main menu thread
        MainMenu main = new MainMenu();
        main.setVisible(true);
        splash.dispose();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_img_splashscreen_icon;
    private javax.swing.JPanel panel_splashscreen_bottom;
    private javax.swing.JProgressBar progressBar_splashscreen;
    // End of variables declaration//GEN-END:variables
}
