/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clamwin.antivirus;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateScanStatus extends javax.swing.JFrame implements WindowListener{
    
    private BufferedImage closeImage = null;
    private BufferedImage minimizeImage = null;
    private int cancelStatus = 1;
    private boolean scanFinished = false;

    /**
     * Creates new form UpdateScanStatus
     */
    public UpdateScanStatus() {
        initComponents();
        iconSet();
        getAndScaleCloseButtonImage();
        getAndScaleMinimizeButtonImage();
        cursorChange();
        addWindowListener(this); 
    }
    
    private void iconSet(){
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/mainIcon.png")));
    }
        
    //scaling the image according to the jlabel
    private void getAndScaleCloseButtonImage(){
        
        try {

            closeImage = ImageIO.read(this.getClass().getResource("/images/closeButton.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
        
	//buffered image scaled
	Image closeBtnDimensions = closeImage.getScaledInstance(lbl_btn_updateScanStatus_close.getWidth(), lbl_btn_updateScanStatus_close.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon closeIcon = new ImageIcon(closeBtnDimensions);
				
	//icon set
	lbl_btn_updateScanStatus_close.setIcon(closeIcon);
        
    }
    
    //scaling the image according to the jlabel
    private void getAndScaleMinimizeButtonImage(){
        
        try {

            minimizeImage = ImageIO.read(this.getClass().getResource("/images/minimize.png"));
            
	} catch (IOException e) {
            
            e.printStackTrace();
            
	}
        
	//buffered image scaled
	Image minimizeBtnDimensions = minimizeImage.getScaledInstance(lbl_btn_updateScanStatus_minimize.getWidth(), lbl_btn_updateScanStatus_minimize.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon MinimizeIcon = new ImageIcon(minimizeBtnDimensions);
				
	//icon set
	lbl_btn_updateScanStatus_minimize.setIcon(MinimizeIcon);
        
    }
    
    //change cursor to hand
    private void cursorChange(){
        lbl_btn_updateScanStatus_close.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lbl_btn_updateScanStatus_minimize.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_updateScanStatus_top = new javax.swing.JPanel();
        lbl_btn_updateScanStatus_close = new javax.swing.JLabel();
        lbl_btn_updateScanStatus_minimize = new javax.swing.JLabel();
        lbl_updateScanStatus_titile = new javax.swing.JLabel();
        panel_updateScanStatus_bottom_main = new javax.swing.JPanel();
        panel_updateScanStatus_bottom_inside = new javax.swing.JPanel();
        panel_updateScanStatus_inside = new javax.swing.JPanel();
        lbl_updateScanStatus_inside_updating = new javax.swing.JLabel();
        progressBar_updateScanStatus_inside = new javax.swing.JProgressBar();
        lbl_updateScanStatus_inside_complete = new javax.swing.JLabel();
        btn_updateScanStatus_cancel = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_updateScanStatus_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_btn_updateScanStatus_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_updateScanStatus_closeMouseClicked(evt);
            }
        });
        panel_updateScanStatus_top.add(lbl_btn_updateScanStatus_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 20));

        lbl_btn_updateScanStatus_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_updateScanStatus_minimizeMouseClicked(evt);
            }
        });
        panel_updateScanStatus_top.add(lbl_btn_updateScanStatus_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 20, 10));

        lbl_updateScanStatus_titile.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lbl_updateScanStatus_titile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_updateScanStatus_titile.setText("ClamWin Virus Database Update");
        lbl_updateScanStatus_titile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_updateScanStatus_top.add(lbl_updateScanStatus_titile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 670, 20));

        getContentPane().add(panel_updateScanStatus_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 20));

        panel_updateScanStatus_bottom_main.setBackground(new java.awt.Color(64, 55, 110));
        panel_updateScanStatus_bottom_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_updateScanStatus_bottom_inside.setBackground(new java.awt.Color(107, 91, 170));
        panel_updateScanStatus_bottom_inside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_updateScanStatus_inside.setBackground(new java.awt.Color(42, 161, 72));
        panel_updateScanStatus_inside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_updateScanStatus_inside_updating.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        lbl_updateScanStatus_inside_updating.setForeground(new java.awt.Color(255, 255, 255));
        lbl_updateScanStatus_inside_updating.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_updateScanStatus_inside_updating.setText("Updating Virus Database File...");
        panel_updateScanStatus_inside.add(lbl_updateScanStatus_inside_updating, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 780, -1));
        panel_updateScanStatus_inside.add(progressBar_updateScanStatus_inside, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 310, 30));

        lbl_updateScanStatus_inside_complete.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        lbl_updateScanStatus_inside_complete.setForeground(new java.awt.Color(255, 255, 255));
        lbl_updateScanStatus_inside_complete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_updateScanStatus_inside_complete.setText("complete");
        panel_updateScanStatus_inside.add(lbl_updateScanStatus_inside_complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 780, 30));

        panel_updateScanStatus_bottom_inside.add(panel_updateScanStatus_inside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 780, 150));

        btn_updateScanStatus_cancel.setBackground(new java.awt.Color(173, 159, 175));
        btn_updateScanStatus_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateScanStatus_cancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_updateScanStatus_cancel.setForeground(new java.awt.Color(255, 0, 0));
        btn_updateScanStatus_cancel.setLabel("Cancel");
        btn_updateScanStatus_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateScanStatus_cancelActionPerformed(evt);
            }
        });
        panel_updateScanStatus_bottom_inside.add(btn_updateScanStatus_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 120, 40));

        panel_updateScanStatus_bottom_main.add(panel_updateScanStatus_bottom_inside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 780, 410));

        getContentPane().add(panel_updateScanStatus_bottom_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //minimize button mouse click action
    private void lbl_btn_updateScanStatus_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_updateScanStatus_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_btn_updateScanStatus_minimizeMouseClicked

    //close button mouse click action
    private void lbl_btn_updateScanStatus_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_updateScanStatus_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_btn_updateScanStatus_closeMouseClicked

    //cancel button mouse click action
    private void btn_updateScanStatus_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateScanStatus_cancelActionPerformed
       
        //if scan is finished
        if(scanFinished){
            
            MainMenu m1 = new MainMenu();
            m1.setVisible(true);
            this.dispose();
            
        }else{
            int userReply;

            userReply = JOptionPane.showConfirmDialog(null,"Are you sure you want cancel the virus database update?", "Cancel Database Update", JOptionPane.YES_NO_OPTION);

            if(userReply == JOptionPane.YES_OPTION){

                cancelStatus = 0;

                JOptionPane updateCancelOptionPane = new JOptionPane("Database Update Cancelled!", JOptionPane.INFORMATION_MESSAGE);

                JDialog updateCancelDialog = updateCancelOptionPane.createDialog(null, "ClamWin Free Antivirus");
                updateCancelDialog.setModal(true);
                updateCancelDialog.setVisible(true);

                MainMenu m1 = new MainMenu();
                m1.setVisible(true);
                this.dispose();

            }else{

            }
        }
        

    }//GEN-LAST:event_btn_updateScanStatus_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateScanStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateScanStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateScanStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateScanStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateScanStatus().setVisible(true);
            }
        });
    }

    //progress bar function
    public void progressBar(){

        //lambda thread creation
        Thread t1 = new Thread(() -> {
            for(int i = 0; i <= 100; i++) {
                try {
                    Thread.sleep(50);
                    lbl_updateScanStatus_inside_complete.setText(Integer.toString(i)+"% complete");
                    progressBar_updateScanStatus_inside.setValue(i);
                    
                    //if cancelled stop the scanning
                    if(cancelStatus == 0){
                        break;
                    }
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
        }
           
        //only display message if not cancelled by the user    
        if(cancelStatus != 0){
            
            scanFinished = true;
            
            //success message
            JOptionPane scanSuccessOptionPane = new JOptionPane("The virus database has been updated successfully !", JOptionPane.INFORMATION_MESSAGE);

            JDialog scanSuccessDialog = scanSuccessOptionPane.createDialog(null, "ClamWin Free Antivirus");
            scanSuccessDialog.setModal(true);
            scanSuccessDialog.setVisible(true);
            
        }
                
        });

        t1.start();
                        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_updateScanStatus_cancel;
    private javax.swing.JLabel lbl_btn_updateScanStatus_close;
    private javax.swing.JLabel lbl_btn_updateScanStatus_minimize;
    private javax.swing.JLabel lbl_updateScanStatus_inside_complete;
    private javax.swing.JLabel lbl_updateScanStatus_inside_updating;
    private javax.swing.JLabel lbl_updateScanStatus_titile;
    private javax.swing.JPanel panel_updateScanStatus_bottom_inside;
    private javax.swing.JPanel panel_updateScanStatus_bottom_main;
    private javax.swing.JPanel panel_updateScanStatus_inside;
    private javax.swing.JPanel panel_updateScanStatus_top;
    private javax.swing.JProgressBar progressBar_updateScanStatus_inside;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        progressBar();
    }

    @Override
    public void windowClosing(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
